-- MySQL Script generated by MySQL Workbench
-- Wed Sep 18 12:24:15 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`notification`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`notification` ;

CREATE TABLE IF NOT EXISTS `mydb`.`notification` (
  `idnotification` INT NOT NULL AUTO_INCREMENT,
  `class` VARCHAR(45) NOT NULL,
  `tittle` VARCHAR(255) NULL,
  PRIMARY KEY (`idnotification`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`role` ;

CREATE TABLE IF NOT EXISTS `mydb`.`role` (
  `idrole` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idrole`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`role_has_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`role_has_user` ;

CREATE TABLE IF NOT EXISTS `mydb`.`role_has_user` (
  `role_idrole` INT NOT NULL,
  `user_iduser` INT NOT NULL,
  PRIMARY KEY (`role_idrole`, `user_iduser`),
  INDEX `fk_role_has_user_user1_idx` (`user_iduser` ASC) VISIBLE,
  INDEX `fk_role_has_user_role1_idx` (`role_idrole` ASC) VISIBLE,
  CONSTRAINT `fk_role_has_user_role1`
    FOREIGN KEY (`role_idrole`)
    REFERENCES `mydb`.`role` (`idrole`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_role_has_user_user1`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `mydb`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`user` ;

CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NULL,
  `class` VARCHAR(45) NOT NULL,
  `list_idlist` INT NOT NULL,
  `notification_idnotification` INT NOT NULL,
  PRIMARY KEY (`iduser`),
  INDEX `fk_user_notification1_idx` (`notification_idnotification` ASC) VISIBLE,
  CONSTRAINT `fk_user_notification1`
    FOREIGN KEY (`notification_idnotification`)
    REFERENCES `mydb`.`notification` (`idnotification`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user_has_widget`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`user_has_widget` ;

CREATE TABLE IF NOT EXISTS `mydb`.`user_has_widget` (
  `user_iduser` INT NOT NULL,
  `widget_idwidget` INT NOT NULL,
  `paid` TINYINT NULL DEFAULT 0,
  PRIMARY KEY (`user_iduser`, `widget_idwidget`),
  INDEX `fk_user_has_widget_widget1_idx` (`widget_idwidget` ASC) VISIBLE,
  INDEX `fk_user_has_widget_user1_idx` (`user_iduser` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_widget_user1`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `mydb`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_widget_widget1`
    FOREIGN KEY (`widget_idwidget`)
    REFERENCES `mydb`.`widget` (`idwidget`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`widget`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`widget` ;

CREATE TABLE IF NOT EXISTS `mydb`.`widget` (
  `idwidget` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `class` VARCHAR(45) NOT NULL,
  `description` VARCHAR(255) NULL,
  `price` INT NULL,
  `paid` TINYINT NULL,
  `notification_idnotification` INT NOT NULL,
  `start` DATETIME NULL,
  `end` DATETIME NULL,
  PRIMARY KEY (`idwidget`),
  INDEX `fk_widget_notification1_idx` (`notification_idnotification` ASC) VISIBLE,
  CONSTRAINT `fk_widget_notification1`
    FOREIGN KEY (`notification_idnotification`)
    REFERENCES `mydb`.`notification` (`idnotification`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
